SRC = $(wildcard *.c)

all:$(SRC:.c=.o)
	gcc hw0501.o poker.o -o hw0501




	make clean

.PHONY : new zip clean cleanexe

new:
	cp ../template.c hw0.c
	code hw0.c

zip:
	zip hw04 ./*.c ./*.pdf ./*.h makefile

clean:
	@-rm *.o

cleanexe:
	@-rm hw040?